import { useBuyerStore } from '../store/buyerStore';

export const useBuyer = () => {
  const {
    wishlist,
    cartSummary,
    orders,
    notifications,
    loadingWishlist,
    loadingCart,
    loadingOrders,
    loadingNotifications,
    errorWishlist,
    errorCart,
    errorOrders,
    errorNotifications,
    fetchWishlist,
    removeFromWishlist,
    fetchCart,
    updateCartItemQuantity,
    removeCartItem,
    clearCart,
    placeOrder,
    fetchOrders,
    fetchNotifications,
    markNotificationRead,
    markAllNotificationsRead,
    deleteNotification,
  } = useBuyerStore();

  return {
    wishlist,
    cartSummary,
    orders,
    notifications,
    loadingWishlist,
    loadingCart,
    loadingOrders,
    loadingNotifications,
    errorWishlist,
    errorCart,
    errorOrders,
    errorNotifications,
    fetchWishlist,
    removeFromWishlist,
    fetchCart,
    updateCartItemQuantity,
    removeCartItem,
    clearCart,
    placeOrder,
    fetchOrders,
    fetchNotifications,
    markNotificationRead,
    markAllNotificationsRead,
    deleteNotification,
  };
};
